database:
  provider: mysql
  host: 127.0.0.1
  port: 3306
  db_name: backupman
  user: root
  password: root
  tls: false

data_sources:
  - provider: mysql
    label: MySQL 1
    host: 127.0.0.1
    port: 3306
    db_name: backupman
    user: root
    password: root
    tmp_folder: ./tmp/mysql
    tls: false

drives:
  - provider: local
    label: Local Drive
    folder: ./tmp/drive
  - provider: google_drive
    label: Google Drive
    folder: demo
    service_account: ./service-account.json

notifiers:
  mail:
    enabled: true
    smtp_host: smtp.example.com
    smtp_port: 587
    smtp_user: user
    smtp_password: password
    smtp_crypto: ssl
    destinations:
      - name: Admin
        email: admin@yopmail.fr
      - name: Admin 2
        email: admin2@yopmail.fr
  webhooks:
    enabled: true
    endpoints:
      - name: My Webhook
        url: http://localhost:8080/webhook
        token: xxx

retention:
  enabled: true
  by: age
  value: 30 #day

http:
  app_url: http://localhost:8080
  api_keys:
    - apikey1
  # Warning: The cron automation is currently part of the HTTP server. In the future, this will be a standalone feature.
  backup_job:
    enabled: true
    cron: "* * * * * *"
