import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: "autogenerated", dirName: "docs" }],
  referencesSidebar: [{ type: "autogenerated", dirName: "references" }],
};

export default sidebars;
