import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "overview",
    "quickstart",
    {
      type: "category",
      label: "Installation",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: ["installation/manual", "installation/docker"],
    },
    "internal-database",
    "data-sources",
    {
      type: "category",
      label: "Drive",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: ["drive/local-drive", "drive/google-drive", "drive/s3-drive"],
    },
    "notifiers",
    "retention-policies",
    "http",
    "scheduled-backups",
    "cli",
  ],
  referencesSidebar: [{ type: "autogenerated", dirName: "references" }],
};

export default sidebars;
