name: Merge Pull Request

on:
  pull_request:
    types: ['synchronize', 'opened', 'reopened']
    branches:
      - main
    paths-ignore:
      - .github/workflows/release.yml

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go get .

      - name: Test
        run: go test ./...
