name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go get .

      - name: Test
        run: go test ./...

      - name: Release 
        uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
          allow-initial-development-versions: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
